version: '3.7'

services:
  heatingcontrol:
    build:
      context: ./
      dockerfile: Dockerfile
    image: heatingcontrol:local
    depends_on:
      - mosquitto
    environment:
      CONFIG_PATH: /opt/app/config/config.yaml
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
    volumes:
      - ./config.yaml:/opt/app/config/config.yaml
    command:
      - /bin/sh
      - -c
      - |
        chmod +x ./bin/heatingcontrol
        ./bin/heatingcontrol -config=$$CONFIG_PATH
  mosquitto:
    image: toke/mosquitto
    ports:
      - 1883:1883
